### ISSUE TITLE
[Improvement] 搜索注入模块优化

### ISSUE THREAD

**Issue by dingyi222666** [dingyi222666/koishi-plugin-chathub#14]
考虑学习 https://github.com/LlmKira/Openaibot/blob/5e83f35abe80e18b3b7fa0fa72deccb3b14da80f/utils/Detect.py#L3

或者其他方式? 目前每次聊天都要搜一遍对上下文影响太大了

**Comment by sudoskys** [comment]
正在实现一种专为异步设计的PipeLine！

**Comment by dingyi222666** [comment]
> 正在实现一种专为异步设计的PipeLine！

简单了解了一下相关的东西，我觉得我需要重构我的大部分实现，这个issue就关闭算了，新开一个issue

**Comment by dingyi222666** [comment]
重新打开issue，因为如果要用其他实现的话需要整体重构（那就是v1版本），为了能让0.x版本能用着还是需要优化一下。

目前0.x暂定实现：回复关键词检查开启搜索，默认关闭搜索，可调用指令额外打开

1.x版本的可能实现：系统prompt告知模型可以搜索，当模型调用搜索指令时给返回结果，然后模型在根据上下文回复对话。完成后删除搜索的结果
