### ISSUE TITLE
[Bug] koishi dev 环境下，webui 中 `模板房间选项` 所有配置均为空

### ISSUE THREAD

**Issue by MirrorCY** [dingyi222666/koishi-plugin-chathub#142]
dev:
![image](https://github.com/ChatLunaLab/chatluna/assets/37006258/3168c9f1-2947-4144-bbd5-09a333714c47)
prod:
![image](https://github.com/ChatLunaLab/chatluna/assets/37006258/a89341bc-d18a-4467-ae72-a945f6e14a98)

```
System:
OS: Windows 10 10.0.19045
CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
Binaries:
Node: 20.11.0
Yarn: 4.1.0
Koishi:
Core: 4.17.1
Console: 5.28.0
```

**Comment by MirrorCY** [comment]
大概是上游问题，类似 https://github.com/koishijs/novelai-bot/issues/226

**Comment by dingyi222666** [comment]
请问是模板项目 + clone 源码 + `yarn start dev` 方式吗？ 
我看一下我这边是否可以复现。

**Comment by MirrorCY** [comment]
是的
- yarn create koishi
- readme 里的流程
- yarn dev
- 观察配置项

**Comment by dingyi222666** [comment]
经过测试，发现 ChatLuna 本身是有正常的获取到相关配置（模型，聊天模式等），问题出在上游 (Koishi)。

403 错误则是因为上面的模板房间配置不正确，导致 ChatLuna 认为没有配置模板房间。（实际上此错误的抛出是正确的，因为确实是没有正确配置模板房间）

建议向上游反馈此错误。

**Comment by 255doesnotexist** [comment]
我以为这是正常现象呢... 每次我都是配置好adapter然后创建房间解决的。

**Comment by dingyi222666** [comment]
Upstream bug related to https://github.com/koishijs/koishi/issues/1382

Please follow there.
