### ISSUE TITLE
[Bug] 文心一言适配器无法正常使用

### ISSUE THREAD

**Issue by Neptune1990** [dingyi222666/koishi-plugin-chathub#143]
chatluna-wenxin-adapter最新版koishi无法正常使用
使用后koishi直接未响应，实用通义千问时正常。
System:
    OS: Windows 10 10.0.19045
    CPU: (20) x64 12th Gen Intel(R) Core(TM) i7-12700

Binaries:
    Node: 20.3.1
    Yarn: 4.0.1

Koishi:
    Core: 4.17.1
    Console: 5.26.6
    Koishi Desktop: 1.0.0

**Comment by dingyi222666** [comment]
过几天我在看一下吧

**Comment by dingyi222666** [comment]
你好，我这边测试没有发现相关问题。有没有更详细的日志文件？

**Comment by dingyi222666** [comment]
如一周内没有提供更详细的报告文件，则认为此 issue 已修复，将会被我关闭。

**Comment by Neptune1990** [comment]
![image](https://github.com/ChatLunaLab/chatluna/assets/107494041/b1012eb1-b572-48ec-bf3a-055044cae9c9)
随后koishi无响应 需重启。
使用的数据库为MySQL。

**Comment by dingyi222666** [comment]
你这日志也没有什么错误信息啊？你的 cache 服务是由 cache-database 提供的吗？

还有我刚才升级了一下文心一言适配器的模型，你可以小火箭更新看一下，看一下新版本是否还有此错误。

**Comment by Neptune1990** [comment]
已解决
