### ISSUE TITLE
[Platform] 适配 MaxKB 平台

### ISSUE THREAD

**Issue by 0Evo** [dingyi222666/koishi-plugin-chathub#171]
https://github.com/1Panel-dev/MaxKB
请求适配这个项目，可以录入知识库进去定制ai

**Comment by dingyi222666** [comment]
有空看看

**Comment by dingyi222666** [comment]
你能否给我一个你在公网可用的该项目的实例?我需要接入测试.我自己实在是没空搭建这个东西.

**Comment by 0Evo** [comment]
> 你能否给我一个你在公网可用的该项目的实例?我需要接入测试.我自己实在是没空搭建这个东西.

qq私你了

**Comment by dingyi222666** [comment]
https://maxkb.cn/pricing.html

发现开放 api 只在其的《专业版》拥有，故不考虑接入该平台
