### ISSUE TITLE
应当让「isNickname」（昵称/@触发聊天）的中间件最后处理消息

### ISSUE THREAD

**Issue by Ikaleio** [dingyi222666/koishi-plugin-chathub#200]
## 问题描述

由于非前置非临时中间件间调用顺序的不确定性，如果其他插件也注册了类似中间件，容易导致多个插件重复回复同一条消息。

可能听起来很抽象，但可以看图：

![BEC4EFACADB9DCB25FB1C6440FD0E072](https://github.com/user-attachments/assets/469993c1-5648-4989-a4f0-2699909df676)

查询源代码可知，`wordle-game` 插件用于处理猜词的中间件的确会在满足猜词条件下阻止后继中间件的执行，但由于调用顺序不确定，ChatLuna 先于 `wordle-game` 调用了中间件。

## 解决方案

响应消息的中间件调用时先注册一个临时中间件，然后直接 `return next()`，将真正的业务逻辑移到该临时中间件。

**Comment by Ikaleio** [comment]
具体而言，将 [/core/src/index.ts:63-67](https://github.com/ChatLunaLab/chatluna/blob/b874efe07520658ed73091c94cf78430398bb2e2/packages/core/src/chains/chain.ts#L63-L67) 做如下更改似乎足矣。

```ts
return next(async _ => {
    const result = await this._runMiddleware(session, context)
    await context.recallThinkingMessage()
    return result
})
```

不太熟悉 Koishi，因此只是把可能的解决方案丢在这里了，没发 PR。qaq

**Comment by dingyi222666** [comment]
好的，我会尝试触发下此 bug，然后使用你的方法查看是否能修复。

**Comment by dingyi222666** [comment]
已发布新版本，你可以更新下查看修好了没有。

**Comment by Ikaleio** [comment]
已修复。
