### ISSUE TITLE
[Bug] 流式传输配合OpenAI适配器，bot出现重复的回复

### ISSUE THREAD

**Issue by AlisaCat-S** [dingyi222666/koishi-plugin-chathub#209]
对接的是claude3.5转的openai格式API，用lobechat没发现问题，如果需要测试可提供API
主程序版本Koishi/4.17.10
插件版本1.0.0/beta61
适配器适配器koishi-plugin-chatluna-openai-like-adapter 1.0.0-beta.14
[问题图片]
![Image_1722255196465](https://github.com/user-attachments/assets/65cb9513-ab3e-49f5-af89-bd19a8cb1d61)

测试关闭流式传输无此问题

**Comment by AlisaCat-S** [comment]
不是每一句话都会出现此bug，通常出现在bot回复的第一句话，并且该句话只有一行字的情况下

**Comment by dingyi222666** [comment]
你好，我需要你的 API 测试，方便加群了解一下：282381753

**Comment by AlisaCat-S** [comment]
> 你好，我需要你的 API 测试，方便加群了解一下：282381753

好的
