### ISSUE TITLE
azure-openai-adapter插件apikeys不会填

### ISSUE THREAD

**Issue by HX-Wrdzgzs** [dingyi222666/koishi-plugin-chathub#210]
![Screenshot_20240731_070501_com.huawei.browser_edit_357492161032168.jpg](https://github.com/user-attachments/assets/ab45a5b0-4af2-4833-bcb0-52d999ede031)

Azure提供了密钥，终结点和资源

**Comment by HX-Wrdzgzs** [comment]
模型名称是填部署名还是？

**Comment by dingyi222666** [comment]
此类问题建议进群 282381753 询问。
