### ISSUE TITLE
[Feature] 允许默认将群聊中每个用户分入不同房间

### ISSUE THREAD

**Issue by Ikaleio** [dingyi222666/koishi-plugin-chathub#211]
目前没有办法限制用户使用某一模型，同时用户邀请或加入房间并不需要任何权限，也无需房主或被邀请用户同意，因此无法将 chatluna.room.create/set/join/invite 权限放开，否则会导致用户乱调模型跑光余额或跑到别人房间瞎刷聊天记录。

因此希望可以设置像 beta60 前由 bug 造成的效果那样群聊中每个用户使用自己的房间或同一用户在不同群/机器人私聊均使用同一房间。

**Comment by dingyi222666** [comment]
感觉还是放开 create 权限好点，我研究一下那个权限组，权限组修好了之后就可以正常放开 create 了（默认创建 private room 别人可以进去那个房间）

**Comment by Ikaleio** [comment]
> 感觉还是放开 create 权限好点，我研究一下那个权限组，权限组修好了之后就可以正常放开 create 了（默认创建 private room 别人可以进去那个房间）

能顺手再加个开关设置同一用户在不同频道下均默认使用同一频道就再好不过了

**Comment by dingyi222666** [comment]
> > 感觉还是放开 create 权限好点，我研究一下那个权限组，权限组修好了之后就可以正常放开 create 了（默认创建 private room 别人可以进去那个房间）
> 
> 能顺手再加个开关设置同一用户在不同频道下均默认使用同一频道就再好不过了

目前设置的是优先使用模版克隆房间，这点我确实欠考虑了，应该优先加入用户自己创建的私有房间。

**Comment by dingyi222666** [comment]
好了，配额组修的差不多了，你可以试一下

**Comment by Hoshino-Yumetsuki** [comment]
或者可以根据群聊创建房间，也就是一个群的成员共用一个房间，这样就可以考虑到在不同群内聊天的情况

**Comment by Ikaleio** [comment]
> 或者可以根据群聊创建房间，也就是一个群的成员共用一个房间，这样就可以考虑到在不同群内聊天的情况

这就是现在的默认情况

**Comment by dingyi222666** [comment]
再次考虑。

**Comment by dingyi222666** [comment]
只在新创建房间时可使用，后期稳定一个房间。
推荐 wipe 后体验
