### ISSUE TITLE
在QQ中，部分消息无法发送

### ISSUE THREAD

**Issue by Rainscall** [dingyi222666/koishi-plugin-chathub#224]
已经在沙盒中试过了：
![image](https://github.com/user-attachments/assets/77ae2e20-605a-4142-9859-84abf411e393)
但是在QQ里面，这两条消息无法发送，导致无法执行指令：
![image](https://github.com/user-attachments/assets/f98bd62d-2491-4ee0-a509-7ad60a79e466)

如果将outputMode设置成图片，反而能正常发送，但也不是每次都能正常发送

**Comment by dingyi222666** [comment]
我这边使用 napcat 接入可以内容，请问你是使用的 QQ 官方 Bot 吗？

https://forum.koishi.xyz/t/topic/6300

这可能是你想要的解决方案
