### ISSUE TITLE
[Bug] gemini 适配器可能无法轮询

### ISSUE THREAD

**Issue by Recho-design** [dingyi222666/koishi-plugin-chathub#238]
在报429额度用完时，在填写了多个apiKeys的情况下没有自动切换到下一个key，是要设置请求配置模式吗？但两种模式都没有自动切换，不是很清楚要怎样设置

**Comment by dingyi222666** [comment]
你设置 gemini 适配器为轮询模式不能用吗

**Comment by Recho-design** [comment]
![1](https://github.com/user-attachments/assets/643ae1c5-045f-4b6c-ba3e-e7842ec86bfd)
![2](https://github.com/user-attachments/assets/27cd2fc9-785c-4c9e-bdc3-8336d44ca08d)
我设置是这样的

**Comment by dingyi222666** [comment]
你把超时时间拉低，额

**Comment by Recho-design** [comment]
> 你把超时时间拉低，额

拉低了，试了几个数也没效果，后台一直报429，然后回复错误1

**Comment by Recho-design** [comment]
测试了一下，得手动把下面没用的key调到位置0就能正常回复，不是全部key额度都用完了的问题

**Comment by Recho-design** [comment]
重装chatluna之后正常了……

**Comment by NFS688** [comment]
我也遇到了同样的问题，无论是顺序配置还是负载均衡都不会自动切换，重装了也没有效果，已检查api可用性

**Comment by NFS688** [comment]
> 我也遇到了同样的问题，无论是顺序配置还是负载均衡都不会自动切换，重装了也没有效果，已检查api可用性

应该是插件模式下无法正常工作，聊天与browsing模式均正常

**Comment by Recho-design** [comment]
> 我也遇到了同样的问题，无论是顺序配置还是负载均衡都不会自动切换，重装了也没有效果，已检查api可用性

重装好了一会儿之后又不行了，现已更换oneapi中转+类OpenAI适配器，你可以参考下

**Comment by NFS688** [comment]
> > 我也遇到了同样的问题，无论是顺序配置还是负载均衡都不会自动切换，重装了也没有效果，已检查api可用性
> 
> 重装好了一会儿之后又不行了，现已更换oneapi中转+类OpenAI适配器，你可以参考下

解决了，谢谢

**Comment by dingyi222666** [comment]
能不能给我几个无额度的 gemini api key 和一个有额度的 api key，让我测试一下....

**Comment by NFS688** [comment]
> 能不能给我几个无额度的 gemini api key 和一个有额度的 api key，让我测试一下....

这个提供不了...，你可以注册几个谷歌账号，gemini目前都是可以免费使用的，最新的gemini-1.5-pro-exp-0827模型每天调用50次，很快就用完了

**Comment by dingyi222666** [comment]
我测试用 openai-like 适配器，轮询和余额无效弹出 key（需要重试 4 次，也就是适配器填写是重试次数 +1） 都可以触发的
