### ISSUE TITLE
[Help] 无法访问 OpenAI 适配器文档

### ISSUE THREAD

**Issue by LingChen-tsjmdlc** [dingyi222666/koishi-plugin-chathub#248]
## 问题描述
**在配置 openAI 的 ChatGPT 的时候，好像无法访问此页面：**
[这个是有些问题的链接](https://[chatluna.dingyi222666.top](https://chatluna.dingyi222666.top/guide/configure-model-platform/openai.html)/guide/configure-model-platform/openai.html)
## 系统及平台
- 系统：Windows 10 pro 22h2
- 平台：PC端
- 网络环境：代理或者未代理
## 复现过程
1. 打开[本项目网址](https://github.com/ChatLunaLab/chatluna?tab=readme-ov-file)
2. 找到[适配支持](https://github.com/ChatLunaLab/chatluna?tab=readme-ov-file#%E9%80%82%E9%85%8D%E6%94%AF%E6%8C%81)
3. 找到表格的第一个[链接](https://github.com/ChatLunaLab/chatluna/blob/v1-dev/packages/openai-adapter/README.md)并打开
4. 点击[OpenAI 适配器文档](https://chatluna.dingyi222666.top/guide/configure-model-platform/openai.html)
5. 结果无法访问：
![image](https://github.com/user-attachments/assets/721c46d2-b4b8-400e-a340-acde1c445d32)
## 尝试
1. 使用代理（无效）（代理软件 v2ray）
## 问题
所以是网站挂了还是链接挂了？
## 备注
想问问有没有什么群号什么的，在 readme 上面说：产能极为稀缺 ，然后有没有很好的联系方式，

**Comment by LingChen-tsjmdlc** [comment]
对了，如果服务器的费用高昂的话，文档这块可以使用云文档代替，如：飞书、语雀等

**Comment by dingyi222666** [comment]
其实是换网址了但是我忘记更新，`chatluna.dingyi222666.top` -> [chatluna.chat](https://chatluna.chat)，有空我这几天在更新吧。

文档在 github 上部署，使用 vitepress 构建的静态站点，几乎免费(有每月最高上传流量限制)。

**Comment by dingyi222666** [comment]
项目的 readme 已经添加了进群链接，点进去就能加群

**Comment by LingChen-tsjmdlc** [comment]
抱歉，进群链接我还是没有看到（可能是我眼瞎🤣
是 v1-dev 分支下的 Readme 吗？

**Comment by dingyi222666** [comment]
对啊，Join QQ Group 那个 tag....

**Comment by LingChen-tsjmdlc** [comment]
看到了（着实眼瞎
