### ISSUE TITLE
[Feature] 适配 Gemini 的音频、视频、pdf发送（识别）

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [dingyi222666/koishi-plugin-chathub#266]
- https://github.com/google-gemini/cookbook/blob/main/quickstarts/Audio.ipynb
- https://github.com/google-gemini/cookbook/blob/main/quickstarts/Video.ipynb
- https://github.com/google-gemini/cookbook/blob/main/quickstarts/PDF_Files.ipynb

**Comment by dingyi222666** [comment]
Requires full file upload/download support from koishi

**Comment by dingyi222666** [comment]
未来视 Koishi API 程度可能会重新实现。
