### ISSUE TITLE
[bug] 无法正常设置时区

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#268]
在koshi全局设置中设置了UTC+8时区，但是在chatluna调用中始终为UTC+0
无法确定具体问题对象

**Comment by dingyi222666** [comment]
具体描述一下

**Comment by furryaxw** [comment]
> 具体描述一下

在koshi插件全局设置中高级设置里将时区偏移量设置为了480（UTC+8），但是在chatluna预设中调用{date}获取到的依旧是UTC+0

**Comment by dingyi222666** [comment]
将跟随下个版本的发布修复。如新版本发布后仍有问题可以在此 Issue 内回复。

**Comment by DGCK81LNN** [comment]
#278 确保了所有本地时间按照当前 TZ 环境变量的时区计算。在 [Koishi v5 提供更合理的时区管理](https://github.com/koishijs/koishi/issues/1466#issuecomment-2405364512)前，请暂时通过 TZ 环境变量来控制时区。

例如，以下 TZ 值均可设置时区为北京时间（东八区）：

* `Asia/Shanghai`
* `PRC`
* `GMT+8`
