### ISSUE TITLE
[Feature] 支持在上下文层面的输出过滤与对用户的过滤

### ISSUE THREAD

**Issue by Hoshino-Yumetsuki** [dingyi222666/koishi-plugin-chathub#276]
- 目前的过滤器仅在平台适配器层面上进行过滤，希望能直接在上下文中进行过滤。将匹配到的违禁词删除或替换为其他字符以减少负面字符对对话造成的影响。
- 支持对用户的输入过滤以减少输出暴力内容的风险，如全部过滤（即阻止输入，可使用llm或其他方式进行合规性审查）和部分过滤（仅替换违禁词）

**Comment by dingyi222666** [comment]
从模型层面控制

**Comment by Hoshino-Yumetsuki** [comment]
模型有时并不能被系统提示词控制，依然会输出明确要求禁止输出的文本。因此该功能依旧有必要

**Comment by dingyi222666** [comment]
已实现
