### ISSUE TITLE
[Feature] 可选使用英文搜索

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#284]
在搜索时始终翻译为英文搜索，导致实际搜索目标偏差
（不确定是否为插件问题或者模型问题）

**Comment by dingyi222666** [comment]
有没有具体的调试日志看一下（开启 isLog）

**Comment by furryaxw** [comment]
> 有没有具体的调试日志看一下（开启 isLog）

由于隐私原因抱歉无法提供日志

**Comment by dingyi222666** [comment]
你可以尝试更换效果更好的模型。

**Comment by dingyi222666** [comment]
我这边 Prompt 是要求模型输出原始语言的，当遵循指令后使用中文输入时，输出也会是中文。

https://github.com/ChatLunaLab/chatluna/blob/fb519cda2a83cdbc46dbb70f515f02df48c45bd7/packages/search-service/src/chain/browsing_chain.ts#L375

**Comment by dingyi222666** [comment]
新版本的搜索服务插件继续强化 Prompt，尽可能的让模型根据输入的语言来决定输出结果的语言。可以更新试一下效果。
