### ISSUE TITLE
[Feautre] 完善 Author's Note

### ISSUE THREAD

**Issue by N0VI028** [dingyi222666/koishi-plugin-chathub#288]
就和顶部prompt完全一样，只是固定插入在用户最新输入的下面，用于加强越狱和做预填充之类的

**Comment by dingyi222666** [comment]
目前有 AuthorsNote，但是还不能自定义插入位置..

https://github.com/ChatLunaLab/chatluna/blob/v1-dev/packages/core/src/llm-core/prompt/type.ts#L94

等我完善一下就差不多

**Comment by dingyi222666** [comment]
文档在这里：

https://chatluna.chat/guide/preset-system/write-preset.html#%E4%BD%9C%E8%80%85%E6%B3%A8%E9%87%8A

建议开启 isLog，如果出现问题就提个 issue。目前测试功能不保证稳定性
