### ISSUE TITLE
[Bug] 历史记录设置为摘要模式时运行错误

### ISSUE THREAD

**Issue by Doxdrw** [dingyi222666/koishi-plugin-chathub#289]
historyMode设置为仅保存对话的摘要信息时，search-service会报错。在聊天模式为browsing下，用户输入任何内容都会报错，无论模型调用搜索与否。historyMode设置为保存最近的完整对话记录时search-service运行正常。多次调试证明确实是historyMode的问题而与其他配置无关。报错日志如下。
> 2024-10-24 01:27:11 [D] chatluna-search-service need search: false, new question: [skip]
> 
> 2024-10-24 01:27:11 [E] chatluna ====================ChatLunaError:999====================
> 2024-10-24 01:27:11 [E] chatluna TypeError: text.match is not a function
>                             at _Tiktoken.encode (D:\dev\backup\node_modules\koishi-plugin-chatluna\node_modules\js-tiktoken\dist\lite.cjs:103:33)
>                             at ChatLunaChatModel.getNumTokens (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\platform\model.cjs:405:35)
>                             at ChatHubChatPrompt.tokenCounter (D:\dev\backup\node_modules\koishi-plugin-chatluna-search-service\lib\index.cjs:126:58)
>                             at ChatHubChatPrompt._formatWithoutMessagesPlaceholder (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\prompt.cjs:220:42)
>                             at ChatHubChatPrompt.formatMessages (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\prompt.cjs:140:20)
>                             at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>                             at async ChatHubChatPrompt.formatPromptValue (D:\dev\backup\node_modules\@langchain\core\dist\prompts\chat.cjs:151:32)
>                             at async ChatHubLLMChain._call (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\base.cjs:209:25)
>                             at async ChatHubLLMChain.invoke (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\base.cjs:96:22)
>                             at async callChatHubChain (D:\dev\backup\node_modules\koishi-plugin-chatluna\lib\llm-core\chain\base.cjs:242:20)

**Comment by dingyi222666** [comment]
我认为摘要模式已经不符合现在模型长上下文的发展趋势，故新版本中将移除此功能。
