### ISSUE TITLE
[Bug] Author's Note未能触发

### ISSUE THREAD

**Issue by N0VI028** [dingyi222666/koishi-plugin-chathub#291]
在预设中设置Author's Note时，log中没有出现内容，实际回答也没有起效，调整插入的三个设置项也没有变化，写法如下：
```
keywords:
    - chatgpt
    - gpt

prompts:
    - role: system
      content: |-
          You are ChatGPT, a large language model trained by OpenAI.
          Knowledge cutoff: 2021-09
          Current date: {date}

author_notes:
  - content: "你需要先输出“五”，再进行回答"
    insertPosition: 'in_chat'
    insertDepth: 0
    insertionFrequency: 1
```
版本是1.0.0-beta.109

**Comment by dingyi222666** [comment]
![6c39943564d856abd0ea64cbe50437d5](https://github.com/user-attachments/assets/7ec8cd5e-aafb-408d-b6af-541cd6cebbcf)

**Comment by N0VI028** [comment]
感谢，另外，作者注释能否也支持占位符？现在使用{user}会报错TypeError: Cannot read properties of undefined (reading 'user')

**Comment by dingyi222666** [comment]
过几天我看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月27日(周日) 凌晨0:13
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ChatLunaLab/chatluna] [Bug] Author's Note未能触发 (Issue #291)




 
感谢，另外，作者注释能否也支持占位符？现在使用{user}会报错TypeError: Cannot read properties of undefined (reading 'user')

**Comment by dingyi222666** [comment]
弄上了，等新版本就支持了
