### ISSUE TITLE
[Bug] 插件模式向机器人发送图片机器人卡死

### ISSUE THREAD

**Issue by SunnyDesignor** [dingyi222666/koishi-plugin-chathub#300]
插件模式下向机器人发送图片，会导致机器人无响应，所有插件无响应，koishi服务需要重启才能恢复。
向bot发送第一张图片能够正常回应，发送第二张时就会无响应。
版本chatluna 1.0.0-beta.112，在切换到beta.110以及之前版本时问题不会出现。

[2024-10-28-4.log](https://github.com/user-attachments/files/17540250/2024-10-28-4.log)

**Comment by dingyi222666** [comment]
我测试没有出现问题。建议重装 Koishi 后尝试是否还有此错误。

**Comment by SunnyDesignor** [comment]
> 我测试没有出现问题。建议重装 Koishi 后尝试是否还有此错误。

重装后问题仍然出现，多发几次图片，或者chatluna room clear后再发几次图片一定会卡死。我已重装整个koishi，并多次测试，几乎可以肯定这是插件的某个潜在问题。

**Comment by dingyi222666** [comment]
你是否尝试过：

1. 接入其他的 Koishi 聊天平台
2. 在其他机器上安装 Koishi 测试
3. 提供完整的日志

**Comment by dingyi222666** [comment]
你顺便测试一下，其他聊天模式是否会触发。
日志提供截图版本的方便查看。

**Comment by SunnyDesignor** [comment]
> 你是否尝试过：
> 
> 1. 接入其他的 Koishi 聊天平台
> 2. 在其他机器上安装 Koishi 测试
> 3. 提供完整的日志

我使用napcat.shell，onebot适配器，其他的接入没有测试，因为我暂时用不到。

我手上没有其他机器，但是旧版插件在这台设备上没有这个问题。

我已经发送了log文件，应该从启动记录到无响应，更详细的日志在哪，我会提供给你。

**Comment by DGCK81LNN** [comment]
我也在插件模式下发送图片时遇到了类似的问题，但由于程序似乎试图将巨量 base64 数据发送至日志，导致日志无法保存

**Comment by dingyi222666** [comment]
我知道是什么问题了，应该是日志输出大量 base64 的问题，嗯....

**Comment by dingyi222666** [comment]
更新新版本看一下，应该没问题了。

你们测试完没问题之后我就关 issue

**Comment by SunnyDesignor** [comment]
113版本，问题已得到修复
