### ISSUE TITLE
[Feature] 使用api管理向量数据库（低优先级）

### ISSUE THREAD

**Issue by furryaxw** [dingyi222666/koishi-plugin-chathub#303]
应使用API而不是删除本地文件的方式清空数据库，以避免在docker中无法安装在根目录的问题

**Comment by dingyi222666** [comment]
??

什么叫无法安装在根目录，faiss 存储的位置是在 data 底下啊?本身就是本地的向量存储。你可以用 redis stack 或者等我完成其他向量数据库接入

**Comment by furryaxw** [comment]
> ??
> 
> 什么叫无法安装在根目录，faiss 存储的位置是在 data 底下啊?本身就是本地的向量存储。你可以用 redis stack 或者等我完成其他向量数据库接入

我使用的是docker版本的Redis和docker版本的koishi，但是机器人一直在尝试删除本地文件

**Comment by furryaxw** [comment]
@dingyi222666 是否可以重开一下这个issue

**Comment by dingyi222666** [comment]
目前针对长期记忆，已经有相关命令可以使用 `chatluna.memory`。知识库插件也自带相关命令。我认为没有必要再打开此 Issue。



---Original---
From: ***@***.***&gt;
Sent at: 2024年11月26日(Tue) Early Morning3:17
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ChatLunaLab/chatluna] [Feature] 使用api管理向量数据库（低优先级） (Issue #303)




 
@dingyi222666 是否可以重开一下这个issue
