### ISSUE TITLE
[Feature] 让除 qwen-max 模型之外的其他通义千问模型也能调用定时提醒等功能

### ISSUE THREAD

**Issue by Jerry-Z07** [dingyi222666/koishi-plugin-chathub#312]
（手机不好编辑，中途还崩一次，炸毛了）
如果你使用 chatluna-qwen-adapter 调用阿里通义千问的话，你会发现除了 qwen-max 系列模型，其他的模型均无法调用 function calling （最直接的体现就是定时提醒无法设置）

不过这个教程的方法，可以让除 qwen-max 模型之外的其他模型也能调用 function calling
- 安装 openai-like-adapter （文档写的很清楚了：https://chatluna.chat/guide/configure-model-platform/openai-like.html ）
- 进入https://bailian.console.aliyun.com/ （也就是百炼控制台）
随意点进去一个模型的详情，点击“API 示例”，然后你会看到如下界面
![Screenshot_2024-11-17-22-43-38-436_com eg android AlipayGphone](https://github.com/user-attachments/assets/85ab5387-e608-4828-a499-cc6a177a9d86)

- 复制“使用 SDK 调用时需配置的 base_url”的内容（即https://dashscope.aliyuncs.com/compatible-mode/v1 ）
- 回到 koishi 控制台，按下图方式，填入相应内容
![IMG_20241117_224726](https://github.com/user-attachments/assets/1765831d-834d-4e45-80da-fbc0c43e997e)

- 保存配置，并加载 openai-like-adapter 插件
将你所在的房间模型（或者是默认模型）修改为（你设置的适配器平台名称）/qwen-xxx
- 试试效果！（如果需要使用定时提醒，还需要先按照文档设置好（https://chatluna.chat/guide/model-plugin-system/cron.html ）
![Image_1731855535962](https://github.com/user-attachments/assets/3d991426-b7a6-4c72-91fe-2792f44a7014)

**Comment by dingyi222666** [comment]
更新新版本千问适配器，你测试一下可以了没有
