### ISSUE TITLE
[Feature] 接入 www.text-to-speech.cn

### ISSUE THREAD

**Issue by yi03** [dingyi222666/koishi-plugin-chathub#33]
我昨天发现 [kbot的tts模块](https://github.com/Kabuda-czh/koishi-plugin-kbot/tree/master/plugins/kbot/src/basic/tts) 使用的是 www.text-to-speech.cn ，好像是中转的微软的接口。试了试效果还不错。你看要不要试试。
kbot的tts模块好像是5天前才加的，感觉还少了一些接口选项，也许可以过阵子等他完善了再抄他的代码。

**Comment by dingyi222666** [comment]
目前chathub是用的vits服务，针对此，我可能会抽时间编写接入该平台的vits服务插件实现，或等待其他人编写该平台的vits服务插件实现

**Comment by dingyi222666** [comment]
感觉有限制，咱还是放弃吧

![1976d4ba15d3a419940202334e2892ff](https://github.com/dingyi222666/koishi-plugin-chathub/assets/48376989/21bd5ef6-3dd8-4837-b1f6-30318e082945)
