### ISSUE TITLE
[Bug] New Bing 适配器容易出错，不稳定

### ISSUE THREAD

**Issue by 315923876** [dingyi222666/koishi-plugin-chathub#37]
使用newbing插件的时候，请求失败的概率较高，即使我使用了代理，目前是阿里云境外服务器，仍有较高概率请求失败，大概在1/3的样子回复未知错误。另外，这些错误往往不需要做出修复，只需等待一会会重新请求，便可恢复使用。常见返回为UnauthorizedRequest 'Cannot retrieve user status.
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/573634b0-b2d6-4a5c-bba0-df99064be70f)

Sorry, you need to login first to access this service，
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/a21f3ce7-942b-4166-9059-d264fcb3e2ee)

亦或是直接回复空消息
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/f9d6f7e0-a758-4b97-952c-188623a4e0df)

DeepLeo也有崩溃概率
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/b2ab3097-8eac-40ad-97bc-9437db6b7422)

如果是因为网络问题，请问能否增加一个请求失败后自动重新请求的功能

![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/b925398f-9ca9-4e5e-bc1f-61168d0b1669)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/0147f642-b887-4114-a783-c1657783108d)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/34d81c9f-99bc-48da-93ae-014b9a1022f2)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/59136b54-4ca8-4832-8494-1028e234dd60)

**Comment by dingyi222666** [comment]
> 1.能否增加一个开关，让插件选择是否对@进行回复，这样可以方便对bot进行管理
2.在使用关键词和@进行交流的时候，会把关键词和@的QQ号一起输入进去，导致bot经常回复“我并不知道@xxx是是谁，也不知道你为何要@他”
3.也是最难受的。我在使用newbing插件的时候，请求失败的概率较高，即使我使用了代理，甚至是阿里云境外服务器，仍有较高概率请求失败，大概在1/3的样子回复未知错误。另外，这些错误往往不需要做出修复，只需等待一会会重新请求，便可恢复使用。常见返回为：1：UnauthorizedRequest

第一点，已在目前的最新开发版本上更新这个功能，我目前正在努力开发1.0版本，争取能在6月初推出第一个alpha版本
第二点，目前也已经在最新开发版本上更新，如果收到的消息里的艾特，没有找到name的话就会置空（之前是会填入qq号）
第三点，可能是cookie问题，但是也可能是 bing 相关api 更新的问题，bing最近在不断更新，api可能也会变化（也就是说这可能是插件的问题）。请等待我先完成旧的new bing 适配器迁移后，在开始排查和修复相关问题。

等第三点的bug确定修复了之后此issue会被我关闭。

**Comment by 315923876** [comment]
> > 1.能否增加一个开关，让插件选择是否对@进行回复，这样可以方便对bot进行管理
> > 2.在使用关键词和@进行交流的时候，会把关键词和@的QQ号一起输入进去，导致bot经常回复“我并不知道@xxx是是谁，也不知道你为何要@他”
> > 3.也是最难受的。我在使用newbing插件的时候，请求失败的概率较高，即使我使用了代理，甚至是阿里云境外服务器，仍有较高概率请求失败，大概在1/3的样子回复未知错误。另外，这些错误往往不需要做出修复，只需等待一会会重新请求，便可恢复使用。常见返回为：1：UnauthorizedRequest
> 
> 第一点，已在目前的最新开发版本上更新这个功能，我目前正在努力开发1.0版本，争取能在6月初推出第一个alpha版本 第二点，目前也已经在最新开发版本上更新，如果收到的消息里的艾特，没有找到name的话就会置空（之前是会填入qq号） 第三点，可能是cookie问题，但是也可能是 bing 相关api 更新的问题，bing最近在不断更新，api可能也会变化（也就是说这可能是插件的问题）。请等待我先完成旧的new bing 适配器迁移后，在开始排查和修复相关问题。
> 
> 等第三点的bug确定修复了之后此issue会被我关闭。

好的，谢谢你的插件：D

**Comment by dingyi222666** [comment]
对于cookie，你可以直接这样填写：`_U=_U的值`
可能更方便一点。

**Comment by 315923876** [comment]
> 对于cookie，你可以直接这样填写：`_U=_U的值` 可能更方便一点。

不好意思，我没有很理解您的意思。请问您能举个例子吗，假设cookie是[ {1}, {2},{3} ]，是要写_U=_[ {1}, {2},{3} ]吗

**Comment by dingyi222666** [comment]
![2KU5M@JH`K0DHH89`1KL1SS.png](https://img1.imgtp.com/2023/05/25/ngEDhnMq.png)
就是_U=_U的值，这个_U的值就是对于cookie里_U的值

**Comment by 315923876** [comment]
> ![2KU5M@JHK0DHH891KL1SS.png](https://camo.githubusercontent.com/1cc41f10c27f499db09291830d19cbc791a7a7e5f1a27793e7c00f8ff8ffdcb8/68747470733a2f2f696d67312e696d6774702e636f6d2f323032332f30352f32352f6e674544686e4d712e706e67) 就是_U=_U的值，这个_U的值就是对于cookie里_U的值

原来如此，不过我是用cookie editor导出的，似乎他已经帮我排好版了。还是谢谢你

**Comment by dingyi222666** [comment]
现在我已经发布了 1.0.0 alpha 版本，如果可以的话你能新建一个 koishi 实例来测试一下新版的 new bing 适配器的稳定性吗？谢谢了。我这边没搭建 bot 测试稳定性，只在沙盒简单测试了一下。

**Comment by 315923876** [comment]
> 现在我已经发布了 1.0.0 alpha 版本，如果可以的话你能新建一个 koishi 实例来测试一下新版的 new bing 适配器的稳定性吗？谢谢了。我这边没搭建 bot 测试稳定性，只在沙盒简单测试了一下。

好的，我今天晚上测试一下

**Comment by 315923876** [comment]
> 现在我已经发布了 1.0.0 alpha 版本，如果可以的话你能新建一个 koishi 实例来测试一下新版的 new bing 适配器的稳定性吗？谢谢了。我这边没搭建 bot 测试稳定性，只在沙盒简单测试了一下。

你好，请问这个聊了两句之后就不理人了是怎么回事啊，我发什么他都只回复这一句
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/973f81b8-dea5-4b4e-bc64-ce578ce4a022)

![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/88b6f47e-fc5f-4034-b09e-e59922089aa2)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/d5d8d0c7-2bb2-41cf-875e-e6139e5fea53)

![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/b48d17d2-db5d-4d86-9940-8bbc32c15cd9)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/4b52918a-4bb3-4645-8d75-edd68e821a2b)
目前对话次数还是不够多，大概在3个群，聊了七八句就出现了这个错误。除了这个之外，可能问题主要就是响应时间比较长，一般需要50秒以上时间去响应，相比起来直接浏览网页或者使用rr-subing只需要10-20就能得到相应
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/640479b1-0098-4722-8311-10e46bb1b3f5)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/95d3211a-e81b-42b0-99b3-a3a864b9984b)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/1d3bdbfd-fe33-46ec-b6b1-aad8f2a98efc)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/d85a9c69-aaeb-4d51-9751-c208685f7ed9)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/7050055d-4636-46d1-89b5-225f32fee335)

**Comment by dingyi222666** [comment]
1. koishi 使用命令的那些字母都得转小写。 比如 `chathub.setmodel`。
2. 检查下 cache 是否为2.0.0 alpha 版本。
3. 速度慢暂时没有更好的解决办法，1.0 插件是基于目前火热的 LLM 开发框架 LangChain 的，使用相关框架时可能需要初始化东西，会有耗时。我后续可能会尝试优化。

**Comment by 315923876** [comment]
> * koishi 使用命令的那些字母都得转小写。 比如 `chathub.setmodel`。
> * 检查下 cache 是否为2.0.0 alpha 版本。
> * 速度慢暂时没有更好的解决办法，1.0 插件是基于目前火热的 LLM 开发框架 LangChain 的，使用相关框架时可能需要初始化东西，会有耗时。我后续可能会尝试优化。

你好，谢谢你的回复。我继续使用了一天，没有其他问题了。我的cache已经是2.00了。我通过重装使用了一天后，还是再次出现了这个问题😭任何输入都会返回：基于你输入的模型的匹配结果，出现了多个会话，请输入更精确的模型名称
![IMG_7335](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/c1f47481-7b4a-4b00-a2f6-8978e1caaf9a)

**Comment by dingyi222666** [comment]
试一下更新相关插件到 `1.0.0-alpha.2` 及以上

**Comment by 315923876** [comment]
> 试一下更新相关插件到 `1.0.0-alpha.2` 及以上

不好意思，我更新到了alpha2及以上，确实解决了以上问题。但是聊了两句之后仍然报错TAT，目前除了gocq及相关，config之外全为最新。
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/18b1505d-60d5-4e0d-807f-1e76c33e0703)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/9314102c-f570-4131-9331-f39f59c673ef)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/5e859adc-535f-4d8a-adfb-6fd0298a453f)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/c0d60210-f65e-4a3e-b32a-ac7dd8b4c520)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/febddef0-6263-4d5d-b9d9-61440ce4969a)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/068b4cd1-66b1-40e5-ae34-01c3cefd46a7)
