### ISSUE TITLE
[Bug] New Bing 适配器没有短期记忆

### ISSUE THREAD

**Issue by LuoPoAn** [dingyi222666/koishi-plugin-chathub#38]
用new bing搭建了一个koishi机器人，但每次与他对话他都会从1/10开始重新记录，无法连续对话是什么原因？

**Comment by dingyi222666** [comment]
你是否开启了 sydney 模式？在此模式下每次对话都会新建一个对话(使用特殊的对话模式来尝试破解限制)。但是实际上有使用到最近的对话记录。
如果不太理解 sydney 模式，建议关闭此配置项。
(最近想写相关文档，但是没空....)

**Comment by LuoPoAn** [comment]
并没有开启

**Comment by LuoPoAn** [comment]
并没有开启，他现在没有上文记忆
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/019b65e4-ce3d-4143-9e1c-c5c855661720)

**Comment by dingyi222666** [comment]
可以在主插件里开启一下 isLog，然后给我看看输出 log 吗?

顺便提供一下复现此 bug 的步骤，我之前在沙盒测试是没问题的。

**Comment by LuoPoAn** [comment]
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/0b7dd224-30a6-486e-8fec-972601c01181)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/beb7db16-1742-4705-b5e0-15bd35c1fc94)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/753a7de3-808d-4c71-a53c-fc9bdf11bd7f)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/054c0988-842a-4267-8016-c91f72b3ad87)
他并没有记住上文，并且发送完消息数据库内多出了三个conversation

**Comment by dingyi222666** [comment]
真的好奇怪哦这个bug......

在我这竟然没复现出来......

![$P7@7Y8BFGEJN}SF 8NM_KU](https://github.com/dingyi222666/koishi-plugin-chathub/assets/48376989/ff4c86ff-c9d0-4470-9f1e-02dd259dcb21)

**Comment by dingyi222666** [comment]
你用的 cache 插件是 cache-memory 吗？

**Comment by LuoPoAn** [comment]
现在使用的是cache-database，之前用的是cache-memory，都会出现这个bug

**Comment by dingyi222666** [comment]
emmm，我这实在没法复现出来。能不能详细提供下相关配置文件，Log 啥的....

**Comment by LuoPoAn** [comment]
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/2574885d-6471-4821-a0ec-f410c3469695)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/e739eff4-38a0-4640-8d93-8e5b6ab3fa8e)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/83e0e3bf-c572-4e94-b2a6-fe155f3d6103)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/d5ea69bf-8647-4294-9c37-0b935392edd2)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/12831479-4d2d-4080-937e-4349f497d8e5)
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/7f15699d-05c1-42a5-a59c-2c48a9d335d9)
这样可以吗

**Comment by LuoPoAn** [comment]
![image](https://github.com/dingyi222666/koishi-plugin-chathub/assets/121866353/c218aae1-aba0-4861-ae2b-f6493dd2725c)
bug消失了（？）我试着将koishi的插件全部更新，bug不见了（？）

**Comment by dingyi222666** [comment]
怎么这么神奇......，你是更新了哪个插件

**Comment by LuoPoAn** [comment]
简单粗暴的将依赖管理内的全更到了最新

**Comment by dingyi222666** [comment]
这。。。就先算已解决了吧。。。

在我这是一直没复现出来的
