### ISSUE TITLE
[Bug] 无法和 `database-mysql` 相结合使用

### ISSUE THREAD

**Issue by 315923876** [dingyi222666/koishi-plugin-chathub#40]
新版chathub一装之后mysql会报错，1.03,1.01都有这个问题，直接用不了任何指令，包括其他插件的，比如help。😭确认是一装chathub，然后启用就会出现，移除依赖后重启就会消失。另外我去找了下，数据库里没有conversationId这张表。老版本0.5.4没有这个问题。chathub设置全默认，没有装适配器。mysql版本8.0.24
![IMG_7373](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/3d5969ba-dc7d-4486-8b5f-97d70ed70940)
![IMG_7374](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/974803c6-f65f-468a-b174-9aedf06befc8)
![IMG_7375](https://github.com/dingyi222666/koishi-plugin-chathub/assets/115673942/90c71c84-b876-4f7a-9e82-ae8f5e460402)

**Comment by dingyi222666** [comment]
还没试过用 `database-mysql` 插件哈哈，看起来是声明表时候某些列的设置有问题。我这两周会尝试修复的。

**Comment by 315923876** [comment]
> 还没试过用 `database-mysql` 插件哈哈，看起来是声明表时候某些列的设置有问题。我这两周会尝试修复的。

好的，谢谢你。

**Comment by dingyi222666** [comment]
我去，我忘记这个 issue 了。下个版本修
