### ISSUE TITLE
[Feature] RWKV-Runner API 支持

### ISSUE THREAD

**Issue by Lightupsky** [dingyi222666/koishi-plugin-chathub#45]
https://github.com/josStorer/RWKV-Runner
这个项目可以加载rwkv模型，并且兼容OpenAI Api，在目前的最新版上使用OpenAI adapter并且更改了endpoint地址为http://127.0.0.1:8000/v1，发生报错。
![default - Koishi 2023_7_29 13_41_53](https://github.com/ChatHubLab/chathub/assets/98253996/a78cfe19-9cee-46a1-91a1-9f6c169a0465)
（上半部分的fetch failed是端口忘记改了，下半部分是报错内容）
RWKV runner同时会报错INFO:     127.0.0.1:59517 - "GET /v1/models HTTP/1.1" 404 Not Found
rwkv的默认模型名就是gpt-turbo-3.5，应该是路径上有不同，目前是读取不到模型list的

**Comment by dingyi222666** [comment]
等我重构完了之后会尝试修复，谢谢反馈

**Comment by dingyi222666** [comment]
我测试了一下，发现这个 api 貌似根本没有实现 `/models`，后续会类似 chatglm2 那样，单独拎出来一个适配器插件来适配吧。
