### ISSUE TITLE
[Bug] 使用 newbing-adapter 时出现 SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Programmer-Red** [dingyi222666/koishi-plugin-chathub#66]
使用newbing插件，报错如下  koishi版本为4.15.0

<img width="1208" alt="image" src="https://github.com/ChatHubLab/chathub/assets/45087936/e6c652f7-07b6-40bd-91e5-119cc7b7a784">

![image](https://github.com/ChatHubLab/chathub/assets/45087936/0e9e0f33-603d-4a7c-9a5e-812bdd2e167f)

![image](https://github.com/ChatHubLab/chathub/assets/45087936/cd0ff8d8-6f03-4937-9d86-fd0a7863a090)

cookie是cookie editor导出的，确认过能够使用

**Comment by dingyi222666** [comment]
这边建议你用开发者工具抓请求的 cookie。我自己测试可用。

![a825013ff5ac1528ceb0103e5adde72f](https://github.com/ChatHubLab/chathub/assets/48376989/6305c885-2f70-4de8-b51b-d2c03a0f48c9)

![d4539383ce2850a76f55962ac4ef0f0f](https://github.com/ChatHubLab/chathub/assets/48376989/348d6bd9-31cf-44a9-8fd7-f6e73c9033d4)

参考 bard，抓 headers 里面的 cookie 属性的全部值，复制进来。

如果不懂的话就来群 282381753 问。

**Comment by Programmer-Red** [comment]
cookie更改后还是报错，但报错内容不一样

![image](https://github.com/ChatHubLab/chathub/assets/45087936/99e832a6-bcac-4644-99e7-0e53a37c8848)

**Comment by dingyi222666** [comment]
检查一下你的代理配置是否正确

**Comment by Programmer-Red** [comment]
是正常的http代理（公网ip），其他平台和软件测试后均可以正常使用

<img width="644" alt="image" src="https://github.com/ChatHubLab/chathub/assets/45087936/8c95cb54-6079-4922-a0f0-a16b689867e7">

我的koishi使用的是docker部署，会不会是插件需要使用其他端口出网但容器没有映射？

**Comment by Programmer-Red** [comment]
> 是正常的http代理，其他平台和软件测试后均可以正常使用
> 
> <img alt="image" width="644" src="https://user-images.githubusercontent.com/45087936/273365748-8c95cb54-6079-4922-a0f0-a16b689867e7.png">
> 我的koishi使用的是docker部署，会不会是插件需要使用其他端口出网但容器没有映射？

目前只开放了koishi控制台的5140端口

**Comment by dingyi222666** [comment]
docker 里能访问到你这个代理吗？你的代理在你的本地环境里可以访问 new bing 吗？
