### ISSUE TITLE
[Bug] 创建模板房间之前无法进行其他操作

### ISSUE THREAD

**Issue by LuoPoAn** [dingyi222666/koishi-plugin-chathub#83]
安装配置完成后直接向BOT提问或是直接进行room创建都无法完成，出现错误码999
![image](https://github.com/ChatHubLab/chathub/assets/121866353/ab84430f-269c-4869-a49b-567380c2f591)
![image](https://github.com/ChatHubLab/chathub/assets/121866353/d94bcb66-b9c3-4181-9eb1-04c58a2b33c0)
![image](https://github.com/ChatHubLab/chathub/assets/121866353/89351ed1-7c82-4045-b1d4-028d70aef435)
![image](https://github.com/ChatHubLab/chathub/assets/121866353/5c4ee798-8670-47a0-9c4a-3908010386d9)

**Comment by dingyi222666** [comment]
你是启用了两个 chathub 吗？请不要启用两个 chathub 插件。同一个 koishi 实例下只能启用一个 chathub。

**Comment by LuoPoAn** [comment]
只启用了chathub的主插件和newbing平台适配插件
![image](https://github.com/ChatHubLab/chathub/assets/121866353/12771190-6191-4d47-9024-3af39d658648)

**Comment by dingyi222666** [comment]
都是最新版本吗？

**Comment by LuoPoAn** [comment]
![image](https://github.com/ChatHubLab/chathub/assets/121866353/b0a33002-74a4-4934-b9c9-2f4ec8c8801e)

**Comment by dingyi222666** [comment]
emm，看起来有点无法解决。你可以尝试一下整个移除插件后重新安装，，，

**Comment by LuoPoAn** [comment]
重装后还是不行，之前使用koishi desktop的node16时，尝试过下载旧版本，使用也出现此问题

**Comment by dingyi222666** [comment]
node 16 不可能会支持的。。。。方便的话看 readme 加 QQ 群讨论吧。可能需要远程诊断。

**Comment by LuoPoAn** [comment]
好，得等个一会

**Comment by LuoPoAn** [comment]
发现好像直接和bot对话让其创建模板房间后可正常进行对话和创建其他房间的操作，如果没有模板房间则创建房间

**Comment by dingyi222666** [comment]
所以是 chathub 的模板房间相关配置没配置好吗

**Comment by LuoPoAn** [comment]
我的模板房间一直是配置好的，现在是必须要让他自动创建一个房间后才能正常使用

**Comment by dingyi222666** [comment]
你试一下双清，新版本修改了模板房间的逻辑

**Comment by dingyi222666** [comment]
> chathub.wipe

需要执行者有五级权限

**Comment by LuoPoAn** [comment]
chathub.wipe完后还是相同情况，在他自动创建模板房间前无法进行chathub.room.create的操作，依旧出现“执行 resolve_room 时出现错误: Cannot read properties of null (reading 'visibility')”

**Comment by dingyi222666** [comment]
我知道了，你想的是在没自动创建模板房间之前先自己创建房间是吧。。。。

那等我这几天修复一下吧。

目前的话就是先和 bot 对话一次创建起来模板房间就可以😂

**Comment by dingyi222666** [comment]
已在 https://github.com/ChatHubLab/chathub/commit/8b1c5ee7e827bc9edabdfba212dee90c934b8ace 修复，等待下个版本更新。
