### ISSUE TITLE
openai适配器出现错误码1

### ISSUE THREAD

**Issue by LuoPoAn** [dingyi222666/koishi-plugin-chathub#86]
版本都是最新，代理应该是没问题的，v2ray的日志中可以看到请求
![H~M_H%@E}GBU)N4~GXZ$L_F](https://github.com/ChatHubLab/chathub/assets/121866353/623f765a-04a6-4228-9471-de3ed621dd39)
![U 5(Z)QYMXGE678U E$U)8D](https://github.com/ChatHubLab/chathub/assets/121866353/b88923c0-3d74-4b78-a6d8-21898efdc37e)
![UC)1` I 530LYM3V%J~2W@M](https://github.com/ChatHubLab/chathub/assets/121866353/7ca3b153-4645-40b4-9a3c-3a0d41d90f3d)
![F`ATUZ3_~V{WEB(1L@IJ$(N](https://github.com/ChatHubLab/chathub/assets/121866353/2da364bd-187e-4162-8599-d0f9a155b72b)

**Comment by dingyi222666** [comment]
看到你那个 Too many requests 了吗？你的 api 额度用到被限制了。

**Comment by LuoPoAn** [comment]
turbo的限制不应该是3RPM，200RPD吗，今日还未使用过，api的额度还有余

**Comment by dingyi222666** [comment]
但是你日志里面就是这个错误。

**Comment by LuoPoAn** [comment]
出现过此报错
![}GDJ {9$CY FYVA6H7XHV5B](https://github.com/ChatHubLab/chathub/assets/121866353/c3456346-ff59-4c69-b780-153319980f05)

**Comment by dingyi222666** [comment]
看起来是 OpenAI 接口不接受 name 不是英文数字，就出现错误了😓。这两周修复。我不会只看到一个 bug 就发版，一般都是在周末的时候堆积起来发版。

**Comment by LuoPoAn** [comment]
这是beta20的问题嘛，之前使用beta19的时候没有出现过😦

**Comment by dingyi222666** [comment]
这是昵称的问题，，，
