### ISSUE TITLE
插件加载失败，这可能是插件本身的问题所致。请联系插件作者并反馈此问题。

### ISSUE THREAD

**Issue by 1592363624** [dingyi222666/koishi-plugin-chathub#87]
![image](https://github.com/ChatLunaLab/chatluna/assets/50036597/dffec175-94a3-40d1-9677-23a17d8bfd23)

**Comment by dingyi222666** [comment]
没有 log 我怎么诊断

**Comment by dingyi222666** [comment]
未提供进一步的 log，将关闭此 issue。
