### ISSUE TITLE
[Platform] 支持星火助手

### ISSUE THREAD

**Issue by chara006688** [dingyi222666/koishi-plugin-chathub#95]
兼容星火助手api
搞了个助手想整群里

**Comment by dingyi222666** [comment]
现在已经有了 spark 的 api 啊

**Comment by dingyi222666** [comment]
不打算适配非 api 的，因为需要额外去兼容，并且需要去抓取其 api 和相关逻辑。

**Comment by dingyi222666** [comment]
看了一下是类似 GPTs 那样的东西吗？看起来需要重新做适配。。。。。。

**Comment by chara006688** [comment]
> 看了一下是类似 GPTs 那样的 API 吗？看起来需要重新做适配。。。。。。

https://www.xfyun.cn/doc/spark/SparkAssistantAPI.html#_1-%E6%98%9F%E7%81%AB%E5%8A%A9%E6%89%8Bapi%E6%9C%8D%E5%8A%A1%E8%AF%B4%E6%98%8E
整个接口就行了好像

**Comment by dingyi222666** [comment]
是需要重新适配，要在原 spark-adapter 上做适配，，，

**Comment by chara006688** [comment]
> 是需要重新适配，要在原 spark-adapter 上做适配，，，

所以说为什么星火助手有四个参数但只有两个空

**Comment by dingyi222666** [comment]
原来那两个参数放在上面就行了，只能设置一个

**Comment by chara006688** [comment]
> 原来那两个参数放在上面就行了，只能设置一个

顺便问下这是什么问题
![66bd85337fec8a96ecc101c0b3daa7d9](https://github.com/ChatLunaLab/chatluna/assets/99468176/c3a46ba1-3f56-44cf-9a41-2c11e16ab5c3)
![图片](https://github.com/ChatLunaLab/chatluna/assets/99468176/66b8e940-c238-4c86-9fce-6c5c42c18e72)

**Comment by dingyi222666** [comment]
```
chatluna.room.clear 
```

清除聊天记录或者 `` chatluna.wipe `` 双清。双清需要 5 级权限
